ktor:
    development: true
    application:
        modules:
            - com.sourcegraph.revenue.ApplicationKt.module
    deployment:
        port: 8080
        watch:
            - classes
            - resources
