version: '3'

tasks:
  install:
    desc: Install dependencies
    cmds:
      - pnpm install

  lint:
    desc: Lint the code
    deps: [install]
    cmds:
      - echo "No linter configured, skipping lint step"

  build:
    desc: Build the application
    deps: [install]
    cmds:
      - pnpm build

  test:
    desc: Run tests
    deps: [install]
    cmds:
      - echo "No tests configured, skipping test step"

  dev:
    desc: Start development server
    deps: [install]
    cmds:
      - pnpm dev
