[tools]
python = "3.13.7"

[tasks.install]
description = "Install dependencies with uv"
run = "uv sync"

[tasks.dev]
description = "Start Flask development server"
run = "uv run python main.py"
depends = ["install"]
