name: Setup mise
description: Install mise and project tools with caching

inputs:
  working-directory:
    description: Directory containing .mise.toml
    required: true
    default: '.'

runs:
  using: composite
  steps:
    - name: Install mise
      shell: bash
      run: |
        curl https://mise.run | sh
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Cache mise tools
      uses: actions/cache@v4
      with:
        path: ~/.local/share/mise
        key: mise-${{ runner.os }}-${{ hashFiles(format('{0}/.mise.toml', inputs.working-directory)) }}-${{ hashFiles(format('{0}/../.mise.toml', inputs.working-directory)) }}-${{ hashFiles(format('{0}/../../.mise.toml', inputs.working-directory)) }}
        restore-keys: |
          mise-${{ runner.os }}-

    - name: Install tools via mise
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        mise trust
        mise install
        mise exec -- task --version || mise exec -- go install github.com/go-task/task/v3/cmd/task@latest
