[tools]
node = "25.0.0"

[tasks.install]
description = "Install dependencies"
run = "pnpm install --silent"

[tasks.dev]
description = "Start development server"  
run = "pnpm start"
depends = ["install"]
