name: Revenue Demo CI

on:
  workflow_call:
    inputs:
      demo_path:
        description: Path to demo directory (e.g., amp_demos/javascript/react)
        required: true
        type: string
      language:
        description: Language of the demo
        required: true
        type: string
      framework:
        description: Framework of the demo
        required: true
        type: string

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ${{ inputs.demo_path }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup mise
        uses: ./.github/actions/setup-mise
        with:
          working-directory: ${{ inputs.demo_path }}

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ${{ inputs.demo_path }}/node_modules
            ~/.cache/pip
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: deps-${{ inputs.language }}-${{ inputs.framework }}-${{ hashFiles(format('{0}/pnpm-lock.yaml', inputs.demo_path), format('{0}/requirements.txt', inputs.demo_path), format('{0}/build.gradle*', inputs.demo_path)) }}
          restore-keys: |
            deps-${{ inputs.language }}-${{ inputs.framework }}-

      - name: Run lint
        run: mise exec -- task lint

  build:
    name: Build
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ${{ inputs.demo_path }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup mise
        uses: ./.github/actions/setup-mise
        with:
          working-directory: ${{ inputs.demo_path }}

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ${{ inputs.demo_path }}/node_modules
            ~/.cache/pip
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: deps-${{ inputs.language }}-${{ inputs.framework }}-${{ hashFiles(format('{0}/pnpm-lock.yaml', inputs.demo_path), format('{0}/requirements.txt', inputs.demo_path), format('{0}/build.gradle*', inputs.demo_path)) }}
          restore-keys: |
            deps-${{ inputs.language }}-${{ inputs.framework }}-

      - name: Run build
        run: mise exec -- task build

  test:
    name: Test
    runs-on: ubuntu-24.04
    needs: build
    defaults:
      run:
        working-directory: ${{ inputs.demo_path }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup mise
        uses: ./.github/actions/setup-mise
        with:
          working-directory: ${{ inputs.demo_path }}

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ${{ inputs.demo_path }}/node_modules
            ~/.cache/pip
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: deps-${{ inputs.language }}-${{ inputs.framework }}-${{ hashFiles(format('{0}/pnpm-lock.yaml', inputs.demo_path), format('{0}/requirements.txt', inputs.demo_path), format('{0}/build.gradle*', inputs.demo_path)) }}
          restore-keys: |
            deps-${{ inputs.language }}-${{ inputs.framework }}-

      - name: Run tests
        run: mise exec -- task test
