name: Shellcheck

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    name: Shellcheck
    steps:
      - uses: actions/checkout@v4
      
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: '.'
          additional_files: 'revenue amp_demos/demo'
          severity: warning
        env:
          SHELLCHECK_OPTS: -e SC1091 -e SC2034
